#! /bin/sh

BSPDIR="$HOME/.config/bspwm"

#export bspwm/bin  dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"
export XDG_CURRENT_DESKTOP='bspwm'

## Bspwm colors
FOCUS_BORDER_COLOR='#252525'
NORMAL_BORDER_COLOR='#11111'
ACTIVE_BORDER_COLOR='#B48EAD'
FEEDBACK_COLOR='#A3BE8C'

## Apply bspwm configurations
# bspc monitor -d '' '' '' '' '' '' '' ''
bspc monitor -d '1' '2' '3' '4' '5'

bspc config border_width 1
bspc config window_gap 10 
bspc config split_ratio 0.50

bspc config focused_border_color "$FOCUS_BORDER_COLOR"
bspc config normal_border_color "$NORMAL_BORDER_COLOR"
bspc config active_border_color "$ACTIVE_BORDER_COLOR"
bspc config presel_feedback_color "$FEEDBACK_COLOR"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
rspc config presel_feedback true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------------#

## remove all rules first
bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
bspc rule -a Wezterm desktop='^1' follow=on focus=on
bspc rule -a Kitty desktop='^1' follow=on focus=on

## 2 > web (always open web browser on workspace-2)
# bspc rule -a firefox desktop='^2' follow=on focus=on
# bspc rule -a chromium desktop='^2' follow=on focus=on

## 3 > files (always open file manager on workspace-3)
declare -a files=(Pcmanfm Thunar qBittorrent)
for i in "${files[@]}"; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

## Always Floating Apps
declare -a floating=(Pcmanfm Thunar Yad 'Firefox:Places' \
Viewnior feh nm-connection-editor)
for i in "${floating[@]}"; do
   bspc rule -a $i state=floating follow=on focus=on; done

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

## Autostart -------------------------------------------------------#

pgrep -x sxhkd >/dev/null || sxhkd &

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager pasystray bspc
# nitrogen --restore &

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

#Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_R|F1' &

# Restore wallpaper
bash ~/.fehbg &

### Status bar
# fix padding
bspc config bottom_padding 0
bspc config top_padding 0
bash "$BSPDIR/polybar/launch.sh"

## Compositor
# Terminate if picom is already running
killall -q picom

# Wait until the processes have been shut down
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done

# Launch picom
picom --config "$BSPDIR/picom.conf" &

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# Enable power management
xfce4-power-manager &

# Enable network
nm-applet &

# Enable bluetooth
blueman-applet &

# Enable volumen
pasystray &

# Notification
if [[ `pidof dunst` ]]; then
	pkill dunst
fi
dunst --config "$DIR/dunstrc" &

## All windows are floating on desktop 8
FLOATING_DESKTOP_ID=$(bspc query -D -d '^5')

bspc subscribe node_add | while read -a msg ; do
   desk_id=${msg[2]}
   wid=${msg[4]}
   [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done
