#!/usr/bin/env bash

OPENDIR="$HOME/.config/openbox"
BSPDIR="$HOME/.config/bspwm"

#export scripts/bin  dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"

## Kill if already running
killall -9 xsettingsd picom mpd dunst ksuperkey xfce4-power-manager nm-applet blueman-applet pasystray

## Restore Wallpaper
# nitrogen --restore
bash ~/.fehbg &

## xfce4-settings daemon
xsettingsd --config="$OPENDIR/xsettingsd" &

## polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
  /usr/lib/xfce-polkit/xfce-polkit &
fi

## Enable power management
xfce4-power-manager &

# Enable network
nm-applet &

# Enable bluetooth
blueman-applet &

# Enable volumen
pasystray &

## Start Compositing Manager
exec picom --config "$OPENDIR/picom.conf" &

## Launch polybar
bash "$OPENDIR/polybar/launch.sh"

## Notification Daemon
# exec dunst &
exec dunst --config "$OPENDIR/dunstrc" &

## Start Music Player Daemon
# exec mpd &

## Thunar Daemon
exec thunar --daemon &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

## These applets are specifically for tint2 panel.
## If you're using tint2 as panel, Uncomment these applets.

## User Friendly Network Menu
#nm-applet --indicator &

## User Friendly Bluetooth Menu
#blueman-applet &
